baseURL = "https://ethicalfrenchie.com/"
copyright = "Ethical Frenchie LLC"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Ethical Frenchie | French Bulldogs For Sale"

SectionPagesMenu = "main"
summarylength = 10

[permalinks]
  blog = "/:title/"


[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  OpenLinksInNewWindow = true
  social = "ethicalfrenchie"
  description = "Find the best french bulldogs for sale over the phone or in person. Vigorous qualification standards. Applications required. Call now (800) 205-7859."

[author]
  name = "James Harrison"
  email = "adopt@ethicalfrenchie.com"
  dev = "Juan Villela"
  devEmail = "hello@juanvillela.me"

[params.google]
  analytics = ""
  tagManager = ""
  adsense = ""

[outputs]
  home = ["html"]
  section = ["html"]
